"""
Download Manager — Endometrial Receptivity Database
"""

import json
from pathlib import Path

import pandas as pd
import streamlit as st

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Download Manager | Endometrial Receptivity DB",
    layout="wide",
    page_icon="⬇️",
    initial_sidebar_state="collapsed",
)

# ---------------------------------------------------------------------------
# Auth guard
# ---------------------------------------------------------------------------
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from auth import check_password

if not check_password():
    st.stop()

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
APP_DIR = Path(__file__).parent.parent
REPO_ROOT = APP_DIR.parent.parent
OUTPUT_DIR = REPO_ROOT / "output"
REGISTRY_PATH = OUTPUT_DIR / "datasets_registry.json"

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DUKE_BLUE = "#00539B"
DUKE_NAVY = "#012169"
DUKE_GOLD = "#B5A369"
DUKE_GREY = "#666666"

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
@st.cache_data(ttl=3600)
def load_downloadable_datasets() -> pd.DataFrame:
    """Load GOLD and SILVER datasets from registry."""
    if not REGISTRY_PATH.exists():
        return pd.DataFrame()

    with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
        raw = json.load(f)

    if isinstance(raw, dict) and "datasets" in raw:
        items = raw["datasets"]
    elif isinstance(raw, list):
        items = raw
    else:
        items = list(raw.values())

    rows = []
    for item in items:
        tier = (item.get("confidence_tier") or item.get("tier") or "").upper()
        if tier not in ("GOLD", "SILVER"):
            continue

        acc = (
            item.get("accession") or item.get("Accession")
            or item.get("dataset_id") or item.get("ID") or ""
        )
        rows.append({
            "accession": acc,
            "title": item.get("title") or item.get("Title") or item.get("study_title") or acc,
            "modality": item.get("modality") or item.get("Modality") or item.get("data_type") or "",
            "tier": tier,
            "file_size_gb": item.get("file_size_gb") or item.get("size_gb") or None,
            "download_url": item.get("download_url") or item.get("url") or item.get("ftp_url") or "",
            "controlled_access": str(
                item.get("controlled_access") or item.get("access_type") or ""
            ).lower() in ("true", "yes", "controlled", "restricted", "1"),
            "md5": item.get("md5") or item.get("checksum") or "",
            "platform": item.get("platform") or item.get("Platform") or "",
        })

    return pd.DataFrame(rows) if rows else pd.DataFrame()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _format_size(gb) -> str:
    if gb is None or (isinstance(gb, float) and pd.isna(gb)):
        return "Unknown"
    try:
        gb = float(gb)
        if gb >= 1:
            return f"{gb:.1f} GB"
        return f"{gb*1024:.0f} MB"
    except (ValueError, TypeError):
        return str(gb)


def _generate_shell_script(selected: pd.DataFrame) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# Endometrial Receptivity Database — Download Script",
        "# Generated by Hickey Lab | Duke University",
        "# Modify OUTPUT_DIR to change download destination",
        "",
        'OUTPUT_DIR="${1:-./downloads}"',
        "mkdir -p \"$OUTPUT_DIR\"",
        "",
    ]
    for modality, grp in selected.groupby("modality"):
        lines.append(f"# ── {modality} ──────────────────────────────────────────")
        for _, row in grp.iterrows():
            acc = row["accession"]
            url = row["download_url"]
            md5 = row.get("md5", "")
            if row.get("controlled_access"):
                lines.append(f"# WARNING: {acc} is controlled-access — manual dbGaP/EGA request required")
                lines.append(f"# URL: {url or 'N/A'}")
            else:
                if md5:
                    lines.append(f"# MD5: {md5}")
                if url:
                    lines.append(f'wget -c -P "$OUTPUT_DIR" "{url}"  # {acc}')
                else:
                    lines.append(f"# {acc}: no direct download URL available")
        lines.append("")
    lines.append("echo 'Download complete.'")
    return "\n".join(lines)


def _generate_python_script(selected: pd.DataFrame) -> str:
    lines = [
        '"""Endometrial Receptivity Database — Python Download Script',
        "Generated by Hickey Lab | Duke University",
        '"""',
        "",
        "import os",
        "import subprocess",
        "import sys",
        "",
        'OUTPUT_DIR = sys.argv[1] if len(sys.argv) > 1 else "./downloads"',
        "os.makedirs(OUTPUT_DIR, exist_ok=True)",
        "",
        "datasets = [",
    ]

    for _, row in selected.iterrows():
        acc = row["accession"]
        url = row["download_url"]
        controlled = row.get("controlled_access", False)
        md5 = row.get("md5", "")
        lines.append(
            f'    {{"accession": {acc!r}, "url": {url!r}, '
            f'"controlled": {controlled!r}, "md5": {md5!r}}},'
        )

    lines += [
        "]",
        "",
        "for ds in datasets:",
        '    acc = ds["accession"]',
        '    url = ds["url"]',
        '    if ds["controlled"]:',
        '        print(f"SKIP {acc}: controlled access — request via dbGaP/EGA")',
        "        continue",
        '    if not url:',
        '        print(f"SKIP {acc}: no download URL")',
        "        continue",
        '    dest = os.path.join(OUTPUT_DIR, os.path.basename(url))',
        '    print(f"Downloading {acc} -> {dest}")',
        '    subprocess.run(["wget", "-c", "-O", dest, url], check=True)',
        '    if ds["md5"]:',
        '        print(f"  MD5: {ds[\'md5\']}")',
        "",
        "print('Done.')",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Page
# ---------------------------------------------------------------------------
st.title("⬇️ Download Manager")
st.markdown(
    "Select **GOLD** and **SILVER** datasets to download. "
    "Controlled-access datasets require a separate dbGaP or EGA application."
)

df = load_downloadable_datasets()

if not REGISTRY_PATH.exists():
    st.warning(
        "Registry not found. Run the pipeline first: `python script/run_pipeline.py`",
        icon="⚠️",
    )
    st.stop()

if df.empty:
    st.info("No GOLD or SILVER datasets found in the registry.")
    st.stop()

# ---------------------------------------------------------------------------
# Build editable table
# ---------------------------------------------------------------------------
df_display = df.copy()
df_display.insert(0, "Select", False)

# Mark controlled access rows as non-selectable initially
# (st.data_editor will handle disabled state)
df_display["file_size_gb"] = df_display["file_size_gb"].apply(_format_size)

# Rename for display
df_display = df_display.rename(columns={
    "accession": "Accession",
    "title": "Title",
    "modality": "Modality",
    "tier": "Tier",
    "file_size_gb": "File Size",
    "download_url": "URL",
    "controlled_access": "Controlled Access",
})

# Column config
col_config = {
    "Select": st.column_config.CheckboxColumn("Select", default=False, width="small"),
    "Accession": st.column_config.TextColumn("Accession", width="small"),
    "Title": st.column_config.TextColumn("Title", width="large"),
    "Modality": st.column_config.TextColumn("Modality", width="medium"),
    "Tier": st.column_config.TextColumn("Tier", width="small"),
    "File Size": st.column_config.TextColumn("File Size", width="small"),
    "URL": st.column_config.LinkColumn("URL", width="medium"),
    "Controlled Access": st.column_config.CheckboxColumn("Controlled Access", disabled=True, width="small"),
}

# Disable selection for controlled access rows
disabled_rows = df_display[df_display["Controlled Access"]].index.tolist()

edited = st.data_editor(
    df_display,
    column_config=col_config,
    use_container_width=True,
    hide_index=True,
    disabled=[c for c in df_display.columns if c != "Select"],
    key="download_editor",
)

# ---------------------------------------------------------------------------
# Size estimate
# ---------------------------------------------------------------------------
selected_mask = edited["Select"].fillna(False)
# Also exclude controlled-access from download even if checked
selected_mask &= ~edited["Controlled Access"].fillna(False)

n_selected = int(selected_mask.sum())
n_controlled_checked = int(
    (edited["Select"].fillna(False) & edited["Controlled Access"].fillna(False)).sum()
)

# Map back to original df for script generation
selected_df = df[selected_mask.values].copy()

# Compute total size
def _parse_gb(size_str: str) -> float:
    if not size_str or size_str == "Unknown":
        return 0.0
    try:
        if "GB" in size_str:
            return float(size_str.replace("GB", "").strip())
        if "MB" in size_str:
            return float(size_str.replace("MB", "").strip()) / 1024
    except ValueError:
        pass
    return 0.0

total_gb = sum(_parse_gb(s) for s in edited[selected_mask]["File Size"])

col_info1, col_info2, col_info3 = st.columns(3)
col_info1.metric("Selected Datasets", n_selected)
col_info2.metric("Estimated Total Size", f"{total_gb:.1f} GB" if total_gb > 0 else "Unknown")
if n_controlled_checked > 0:
    col_info3.warning(
        f"{n_controlled_checked} controlled-access dataset(s) excluded from download scripts.",
        icon="🔒",
    )

# Orange badge for controlled access rows
if (df["controlled_access"]).any():
    st.info(
        "Rows marked **Controlled Access** require a manual application to "
        "[dbGaP](https://www.ncbi.nlm.nih.gov/gap) or [EGA](https://ega-archive.org/). "
        "They are excluded from generated scripts.",
        icon="🔒",
    )

st.divider()

# ---------------------------------------------------------------------------
# Script generation buttons
# ---------------------------------------------------------------------------
if n_selected == 0:
    st.info("Select datasets above to generate download scripts.")
else:
    btn_col1, btn_col2 = st.columns(2)

    with btn_col1:
        sh_content = _generate_shell_script(selected_df)
        st.download_button(
            label="Generate Download Script (.sh)",
            data=sh_content.encode("utf-8"),
            file_name="download_manifest.sh",
            mime="text/x-sh",
            use_container_width=True,
            type="primary",
        )
        st.caption("Bash wget script — run with `bash download_manifest.sh [output_dir]`")

    with btn_col2:
        py_content = _generate_python_script(selected_df)
        st.download_button(
            label="Generate Download Script (.py)",
            data=py_content.encode("utf-8"),
            file_name="download_manifest.py",
            mime="text/x-python",
            use_container_width=True,
        )
        st.caption("Python wget wrapper — run with `python download_manifest.py [output_dir]`")

    # Preview
    with st.expander("Preview shell script"):
        st.code(_generate_shell_script(selected_df), language="bash")
